mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^order_manager/', include('order_manager.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^menu/', include('bar_admin.urls')),
    url(r'^bar_tender/', include('bartender_app.urls')),
    #url(r'^client/', include('client_app.urls')),
    url(r'^', include('client_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order_manager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^change-order-status/$', views.changeOrderStatus),
    url(r'^order_status/$', views.orderStatus),
    url(r'^$', views.order, name='order'),
]

order_manager/models.py
from django.db import models
from django.utils import timezone

from django.conf import settings

class Order(models.Model):
    
    PENDING_STATUS = 'P'
    ACCEPTED_STATUS = 'A'
    REFUSED_STATUS = 'R'
    READY_STATUS = 'O'
    CANCELLED_STATUS = 'C'

    STATUS_CHOICES = (
        (PENDING_STATUS, 'Pending'),
        (ACCEPTED_STATUS, 'Accepted'),
        (REFUSED_STATUS, 'Refused'),
        (READY_STATUS, 'Ready'),
        (CANCELLED_STATUS, 'Cancelled')
    )
    
    comment = models.CharField(max_length=200, default="")
    pseudo = models.CharField(max_length=50, default="")
    
    status = models.CharField(max_length=1,
                                      choices=STATUS_CHOICES,
                                      default=PENDING_STATUS)
    requestedTime = models.DateTimeField(default=timezone.now)
    modifiedTime = models.DateTimeField(default=timezone.now)
    
    processedTime = models.DateTimeField(default=timezone.now) #once processed, the order should not be modified anymore
    
    client_user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, blank = True, null=True)

    def __str__(self):
        #return str(self.id + " " + str(self.requestedTime))
        return str(self.id) + self.status
        

#TODO : change the class name :-)
class order_details(models.Model):
    
    name = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    order = models.ForeignKey(Order,null=True) #an order detail must be linked to an order
    def __str__(self):
        return self.name

order_manager/views.py
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponse
from django.core import serializers

from .models import order_details
from .models import Order

from django.conf import settings

from django.core.context_processors import csrf
from django.views.decorators.csrf import ensure_csrf_cookie

from django.http import JsonResponse

import json

from django.contrib.auth.decorators import login_required

def order(request):
    # if not request.user.is_authenticated():
    #     return JsonResponse({'isUserAuthenticated': False })
    # else:
    if request.method == 'POST':
        
        jsonString = request.POST.get('json')
        pseudo = request.POST.get('pseudo')
        comment = request.POST.get('comment')
        
        jsonOrder = json.loads(jsonString)
        
        new_order = Order()
        new_order.pseudo = pseudo
        new_order.comment = comment

        #new_order.client_user = request.user
        
        new_order.save()
                
        for order_item in jsonOrder:
            tmp = order_details(name=order_item['name'],quantity=order_item['quantity'], order = new_order)
            tmp.save()
            
        order_detail_list = order_details.objects.all()
        order_list = Order.objects.all()
        context = {'order_list': order_list, 'order_detail_list': order_detail_list,}
        return JsonResponse({'isUserAuthenticated': True ,'order_id':new_order.id})
                   
    else:
        order_detail_list = order_details.objects.all()
        order_list = Order.objects.all()
        context = {'order_list': order_list, 'order_detail_list': order_detail_list,}

    #return render(request, 'order_manager/order_details.html', context)
    return render_to_response("order_manager/order_details.html",
                              locals(),
                              context_instance=RequestContext(request)
                              )
@login_required
def changeOrderStatus(request):
    
    from django.utils import timezone
    
    if request.method == 'POST':
        orderId = request.POST.get('id')
        newStatus = request.POST.get('status')
        order = Order.objects.get(id = orderId)
        order.status = newStatus
        
        if (newStatus == Order.READY_STATUS or newStatus == Order.REFUSED_STATUS):
            order.processedTime = timezone.now()
        
        order.save()

    return JsonResponse({'status':'ok'})


#@login_required
def orderStatus(request):
    if request.method == 'POST':
        orderId = request.POST.get('id')
    elif request.method == 'GET':
        orderId = request.GET.get('id')
        
    order = Order.objects.get(id = orderId)

    return JsonResponse({'order_status':order.status})

order_manager/templates/order_manager/order_details.html
<h1>Orders</h1>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="/static/js/manage-orders.js"></script>   
    
{% if order_list%}
    <ul>
    {% for order in order_list %}
        <h2>Order {{order.id}} ({{order.status}}) </h2>
        {% if order.order_details_set.all%}
            {% for order_detail in order.order_details_set.all %}
                <li><a>{{order_detail.quantity}} {{ order_detail.name }}</a></li>
            {% endfor %}
        {% else %}
            <p>No item ordered for this order</p>
        {% endif %}
        <button type="button" onclick="acceptOrder({{order.id}});">Accept Order</button>
    {% endfor %}
    </ul>
{% else %}
    <p>No order available.</p>
{% endif %}


{% load static from staticfiles %}
<script src="{% static "js/manage-orders.js" %}"></script>

<script>

  /*************************  
  // security against csrf attack (copied from https://docs.djangoproject.com/en/1.8/ref/csrf/)
  *////////////////////////
  
  // using jQuery
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');
  
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
  });

</script>